### ISSUE TITLE
Use a "calculator" icon for this node instead of "summation" icon.

### ISSUE THREAD

**Issue by janvda** [bartbutenaers/node-red-contrib-calc#1]
I have a small feature request.

You have used https://en.wiktionary.org/wiki/%CE%A3 as symbol for this node.
As this node does much more than calculating the sum of numbers, I think that a "calculator" icon would be better.

**Comment by bartbutenaers** [comment]
Hey Jan,

Yes indeed it started with basic calculations.  
But you know I never stop adding functionality ;-)

I have now changed it to this icon on **Github**:
![image](https://user-images.githubusercontent.com/14224149/49895977-4862ad80-fe52-11e8-846d-c505fbc1e46c.png)

Is that self-explaining enough?

I will publish this on **NPM** as soon as soon as I have time to add other functionalities.

Bart

**Comment by janvda** [comment]
Hi Bart,
That is more than excellent.
Indeed this can of course wait for other functionalities.
Have a nice evening.
Jan

**Comment by bartbutenaers** [comment]
Jan,
Completely overlooked this one...
Is now available on npm as version **1.0.3**
