### ISSUE TITLE
Feature request: log10

### ISSUE THREAD

**Issue by matthewandersonsonos** [bartbutenaers/node-red-contrib-calc#5]
Hi there - really useful addition to Node-RED, but was disappointed to see that log10 was left out. Any chance it could be included in a release in the near future? Thanks!

**Comment by bartbutenaers** [comment]
Hi Matt,
Could you please install version ***1.0.4*** of this node directly from Github and let me know if the log10 option works correctly.  Like this from within your Node-RED directory:
```
npm install bartbutenaers/node-red-contrib-calc
```
I don't have the ability at the moment to test it myself...
Kind regards,
Bart

**Comment by matthewandersonsonos** [comment]
Hi Bart, is there a way to test this as a node in my flow? I'm a bit of a noobie with node-red, so I'm not sure how to test this standalone

**Comment by bartbutenaers** [comment]
Matt, if you have installed it correctly (with my above command), then version 1.0.4 of my node should be available in the Node-RED flow editor (after browser refresh).

**Comment by bartbutenaers** [comment]
Matt,
Version ***1.0.4*** is now available on NPM and in the Node-RED palette.
