### ISSUE TITLE
Rounding doesn't work on any of the functions.

### ISSUE THREAD

**Issue by jimford-sudo** [bartbutenaers/node-red-contrib-calc#6]
I'm using Node-Red v1.1.0 from within Home Assistant, and find that I'm unable to enter a number for the rounding option - it always reverts to zero. I downloaded the node from the Manage Palette menu. 

(This issue seems to have been reported previously for an earlier version of Node-Red, and was subsequently closed. It's a very handy node and thanks to the Developer for providing it.)
Jim

**Comment by bartbutenaers** [comment]
Hi Jim,

Nice catch.  You found a bug ...
I have published version 1.0.5 on NPM that should solve this issue.

![image](https://user-images.githubusercontent.com/14224149/91213490-f63eea00-e711-11ea-9b31-4c66d4a023d5.png)

> This issue seems to have been reported previously for an earlier version of Node-Red, and was subsequently closed. 

Not sure what you mean by this.  Can you please explain that a bit more in detail.
Bart
