### ISSUE TITLE
Round upwards/downwards suggestion

### ISSUE THREAD

**Issue by hspjanssen** [bartbutenaers/node-red-contrib-calc#8]
Great calculator for Node Red, question regarding the round upwards/downwards. Would it be possible to ad a feature to round on decimals, for example:

0.86 -> 0.9
0.84 -> 0.8

Many thanks, keep up the great work!

**Comment by bartbutenaers** [comment]
Hi @hspjanssen,

I think that is already implemented.
See this example flow:

![image](https://user-images.githubusercontent.com/14224149/130335199-702cf275-a0ea-4009-a975-b4e67a6a3d1c.png)
```
[{"id":"b6bc5399.8385e","type":"calculator","z":"cdc96e4688dada0a","name":"","inputMsgField":"payload","outputMsgField":"payload","operation":"rdec","constant":"","round":false,"decimals":0,"x":560,"y":440,"wires":[["4c297cba.7585a4"]]},{"id":"e5a3b930.003428","type":"inject","z":"cdc96e4688dada0a","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[0.86, 1]","payloadType":"json","x":300,"y":440,"wires":[["b6bc5399.8385e"]]},{"id":"4c297cba.7585a4","type":"debug","z":"cdc96e4688dada0a","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":810,"y":440,"wires":[]},{"id":"0ddddf08e54f0a99","type":"inject","z":"cdc96e4688dada0a","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[0.84, 1]","payloadType":"json","x":300,"y":480,"wires":[["b6bc5399.8385e"]]}]
```
Which gives following output:
![image](https://user-images.githubusercontent.com/14224149/130335219-c79694ce-c8cd-443b-a8c5-0f501d2ab74d.png)

Bart

**Comment by hspjanssen** [comment]
Hello,

Thanks for your fast answer, I saw that option, but I thought it "cut" the decimals, according to your description in the "manual":
![round_decimals](https://user-images.githubusercontent.com/32012352/130347151-51e32444-10e4-4c48-aed3-cd91b28b72f3.png)

But in fact the output is not 1.234 but 1.235, so it is really a round upwards, see below example. 

Maybe correct this in the manual?

[{"id":"3e329e777a5729f1","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"abcec1063974eebc","type":"calculator","z":"3e329e777a5729f1","name":"","inputMsgField":"payload","outputMsgField":"payload","operation":"rdec","constant":"","round":false,"decimals":0,"x":440,"y":140,"wires":[["62a3d0bb58bd666d"]]},{"id":"74fa432a4c18f899","type":"inject","z":"3e329e777a5729f1","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[1.23456, 3]","payloadType":"json","x":190,"y":140,"wires":[["abcec1063974eebc"]]},{"id":"62a3d0bb58bd666d","type":"debug","z":"3e329e777a5729f1","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":690,"y":140,"wires":[]},{"id":"043fbafadb856941","type":"inject","z":"3e329e777a5729f1","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[0.845, 2]","payloadType":"json","x":180,"y":180,"wires":[["abcec1063974eebc"]]}]


So that is good news! Now I have to find a way to convert the msg.payload to something like [msg.payload, 3], so this is not as straight forward as divide/substract etc, where msg.payload input is msg.payload as output.

**Comment by bartbutenaers** [comment]
> I thought it "cut" the decimals ... But in fact the output is not 1.234 but 1.235, so it is really a round upwards

Not sure if I understand you correctly.  
The documentation says *"round the number ..."*, which seems correct to me.
Rounding [means](https://www.mathsisfun.com/rounding-numbers.html):

![image](https://user-images.githubusercontent.com/14224149/130369193-14450c0b-3c9e-4b1b-bed4-6a0812cd3a6d.png)


> Now I have to find a way to convert the msg.payload to something like [msg.payload, 3]

Instead of inserting an array `[1.234, 3]`, you can also insert the number `1.234` and set the ***"constant"*** to true:

![image](https://user-images.githubusercontent.com/14224149/130368979-8ca1145c-54e8-4165-aa65-541f261ab413.png)

Example:
```
[{"id":"abcec1063974eebc","type":"calculator","z":"3e329e777a5729f1","name":"","inputMsgField":"payload","outputMsgField":"payload","operation":"rdec","constant":"3","round":false,"decimals":0,"x":440,"y":140,"wires":[["62a3d0bb58bd666d"]]},{"id":"74fa432a4c18f899","type":"inject","z":"3e329e777a5729f1","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"1.23456","payloadType":"json","x":180,"y":140,"wires":[["abcec1063974eebc"]]},{"id":"62a3d0bb58bd666d","type":"debug","z":"3e329e777a5729f1","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":690,"y":140,"wires":[]}]
```

**Comment by hspjanssen** [comment]
Hello,

I can confirm that this is working, so this issue can be closed.

However as I stated earlier, I think the description on your page (https://github.com/bartbutenaers/node-red-contrib-calc) is not correct, see below:

![image](https://user-images.githubusercontent.com/32012352/130501305-a35196ed-c062-4caa-b180-20493613a6e6.png)

The output is 1.235 and not 1.234, this is why I first thought that the function did not round.

Many thanks for the support and keep up the good work!!

Kind regards

**Comment by bartbutenaers** [comment]
Hi @hspjanssen,

I have corrected the rounding typo fix on the readme page, like you have pointed out.
Of course this will only be published on npm, with the next future release of this node.
Until then the 1.234 will be be visible on the NPM readme page...

Bart
